name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci
      - name: Run unit tests and collect coverage
        run: npm run test:coverage

      - name: Upload coverage (lcov)
        uses: actions/upload-artifact@v4
        with:
          # include job name to ensure artifact names are unique per job/run
          name: coverage-lcov-${{ github.job }}
          path: coverage/lcov.info

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info

  build-and-test:
    name: build-and-test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: |
          npm ci
          npm run prepare || true

      - name: Markdown lint
        run: npm run lint:md

      - name: Build (compile & webpack)
        run: |
          npm run compile-tests
          npm run compile

      - name: Lint (auto-fix)
        run: |
          npm run lint:fix || true
          npm run lint

      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v4

      - name: Run tests (inside headless display)
        run: |
          # The setup-headless-display action configures a DISPLAY for the runner.
          # Run the test runner normally; the action ensures a headless X server is available.
          npm test
