name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm ci
          npm run prepare || true

      - name: Markdown lint
        run: npm run lint:md

      - name: Build (compile & webpack)
        run: |
          npm run compile-tests
          npm run compile

      - name: Lint (auto-fix)
        run: |
          npm run lint:fix || true
          npm run lint

      - name: Run tests (inside Xvfb)
        run: |
          # Install X virtual framebuffer so Electron/VS Code can start in CI
          sudo apt-get update
          sudo apt-get install -y xvfb
          # Run tests under xvfb so the VS Code test host has a DISPLAY
          xvfb-run --auto-servernum --server-args='-screen 0 1280x1024x24' npm test
